/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssessmentDto', 'model/AssessmentSummaryDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AssessmentDto'), require('../model/AssessmentSummaryDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.AssessmentsApi = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.AssessmentDto, root.HmppsOffenderAssessmentApi.AssessmentSummaryDto);
  }
}(this, function(ApiClient, AssessmentDto, AssessmentSummaryDto) {
  'use strict';

  /**
   * Assessments service.
   * @module api/AssessmentsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AssessmentsApi. 
   * @alias module:api/AssessmentsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Gets an Assessment by its identity
     * @param {Number} oasysSetId oasysSetId
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AssessmentDto} and HTTP response
     */
    this.getAssessmentUsingGETWithHttpInfo = function(oasysSetId) {
      var postBody = null;

      // verify the required parameter 'oasysSetId' is set
      if (oasysSetId === undefined || oasysSetId === null) {
        throw new Error("Missing the required parameter 'oasysSetId' when calling getAssessmentUsingGET");
      }


      var pathParams = {
        'oasysSetId': oasysSetId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['spring_oauth'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = AssessmentDto;

      return this.apiClient.callApi(
        '/assessments/oasysSetId/{oasysSetId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets an Assessment by its identity
     * @param {Number} oasysSetId oasysSetId
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AssessmentDto}
     */
    this.getAssessmentUsingGET = function(oasysSetId) {
      return this.getAssessmentUsingGETWithHttpInfo(oasysSetId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Gets the latest assessment for an offender
     * @param {String} identity identity
     * @param {String} identityType identityType
     * @param {Object} opts Optional parameters
     * @param {String} opts.assessmentStatus assessmentStatus
     * @param {String} opts.assessmentType assessmentType
     * @param {String} opts.historicStatus historicStatus
     * @param {Boolean} opts.voided voided
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AssessmentDto} and HTTP response
     */
    this.getAssessmentUsingGET1WithHttpInfo = function(identity, identityType, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'identity' is set
      if (identity === undefined || identity === null) {
        throw new Error("Missing the required parameter 'identity' when calling getAssessmentUsingGET1");
      }

      // verify the required parameter 'identityType' is set
      if (identityType === undefined || identityType === null) {
        throw new Error("Missing the required parameter 'identityType' when calling getAssessmentUsingGET1");
      }


      var pathParams = {
        'identity': identity,
        'identityType': identityType
      };
      var queryParams = {
        'assessmentStatus': opts['assessmentStatus'],
        'assessmentType': opts['assessmentType'],
        'historicStatus': opts['historicStatus'],
        'voided': opts['voided'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['spring_oauth'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = AssessmentDto;

      return this.apiClient.callApi(
        '/offenders/{identityType}/{identity}/assessments/latest', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets the latest assessment for an offender
     * @param {String} identity identity
     * @param {String} identityType identityType
     * @param {Object} opts Optional parameters
     * @param {String} opts.assessmentStatus assessmentStatus
     * @param {String} opts.assessmentType assessmentType
     * @param {String} opts.historicStatus historicStatus
     * @param {Boolean} opts.voided voided
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AssessmentDto}
     */
    this.getAssessmentUsingGET1 = function(identity, identityType, opts) {
      return this.getAssessmentUsingGET1WithHttpInfo(identity, identityType, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Gets a list of assessments for an offender
     * @param {String} identity identity
     * @param {String} identityType identityType
     * @param {Object} opts Optional parameters
     * @param {String} opts.assessmentStatus assessmentStatus
     * @param {String} opts.assessmentType assessmentType
     * @param {String} opts.historicStatus historicStatus
     * @param {Boolean} opts.voided voided
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AssessmentSummaryDto>} and HTTP response
     */
    this.getAssessmentsForOffenderUsingGETWithHttpInfo = function(identity, identityType, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'identity' is set
      if (identity === undefined || identity === null) {
        throw new Error("Missing the required parameter 'identity' when calling getAssessmentsForOffenderUsingGET");
      }

      // verify the required parameter 'identityType' is set
      if (identityType === undefined || identityType === null) {
        throw new Error("Missing the required parameter 'identityType' when calling getAssessmentsForOffenderUsingGET");
      }


      var pathParams = {
        'identity': identity,
        'identityType': identityType
      };
      var queryParams = {
        'assessmentStatus': opts['assessmentStatus'],
        'assessmentType': opts['assessmentType'],
        'historicStatus': opts['historicStatus'],
        'voided': opts['voided'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['spring_oauth'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = [AssessmentSummaryDto];

      return this.apiClient.callApi(
        '/offenders/{identityType}/{identity}/assessments/summary', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets a list of assessments for an offender
     * @param {String} identity identity
     * @param {String} identityType identityType
     * @param {Object} opts Optional parameters
     * @param {String} opts.assessmentStatus assessmentStatus
     * @param {String} opts.assessmentType assessmentType
     * @param {String} opts.historicStatus historicStatus
     * @param {Boolean} opts.voided voided
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AssessmentSummaryDto>}
     */
    this.getAssessmentsForOffenderUsingGET = function(identity, identityType, opts) {
      return this.getAssessmentsForOffenderUsingGETWithHttpInfo(identity, identityType, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
