/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RefAssessmentDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/RefAssessmentDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.ReferenceAssessmentApi = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.RefAssessmentDto);
  }
}(this, function(ApiClient, RefAssessmentDto) {
  'use strict';

  /**
   * ReferenceAssessment service.
   * @module api/ReferenceAssessmentApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ReferenceAssessmentApi. 
   * @alias module:api/ReferenceAssessmentApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * getReferenceAssessmentOf
     * @param {String} versionCode versionCode
     * @param {String} versionNumber versionNumber
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RefAssessmentDto} and HTTP response
     */
    this.getReferenceAssessmentOfUsingGETWithHttpInfo = function(versionCode, versionNumber) {
      var postBody = null;

      // verify the required parameter 'versionCode' is set
      if (versionCode === undefined || versionCode === null) {
        throw new Error("Missing the required parameter 'versionCode' when calling getReferenceAssessmentOfUsingGET");
      }

      // verify the required parameter 'versionNumber' is set
      if (versionNumber === undefined || versionNumber === null) {
        throw new Error("Missing the required parameter 'versionNumber' when calling getReferenceAssessmentOfUsingGET");
      }


      var pathParams = {
        'versionCode': versionCode,
        'versionNumber': versionNumber
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['spring_oauth'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = RefAssessmentDto;

      return this.apiClient.callApi(
        '/referenceassessments/type/{versionCode}/revision/{versionNumber}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * getReferenceAssessmentOf
     * @param {String} versionCode versionCode
     * @param {String} versionNumber versionNumber
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RefAssessmentDto}
     */
    this.getReferenceAssessmentOfUsingGET = function(versionCode, versionNumber) {
      return this.getReferenceAssessmentOfUsingGETWithHttpInfo(versionCode, versionNumber)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
