/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HmppsOffenderAssessmentApi);
  }
}(this, function(expect, HmppsOffenderAssessmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AssessmentNeedDto', function() {
      beforeEach(function() {
        instance = new HmppsOffenderAssessmentApi.AssessmentNeedDto();
      });

      it('should create an instance of AssessmentNeedDto', function() {
        // TODO: update the code to test AssessmentNeedDto
        expect(instance).to.be.a(HmppsOffenderAssessmentApi.AssessmentNeedDto);
      });

      it('should have the property flaggedAsNeed (base name: "flaggedAsNeed")', function() {
        // TODO: update the code to test the property flaggedAsNeed
        expect(instance).to.have.property('flaggedAsNeed');
        // expect(instance.flaggedAsNeed).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property overThreshold (base name: "overThreshold")', function() {
        // TODO: update the code to test the property overThreshold
        expect(instance).to.have.property('overThreshold');
        // expect(instance.overThreshold).to.be(expectedValueLiteral);
      });

      it('should have the property riskOfHarm (base name: "riskOfHarm")', function() {
        // TODO: update the code to test the property riskOfHarm
        expect(instance).to.have.property('riskOfHarm');
        // expect(instance.riskOfHarm).to.be(expectedValueLiteral);
      });

      it('should have the property riskOfReoffending (base name: "riskOfReoffending")', function() {
        // TODO: update the code to test the property riskOfReoffending
        expect(instance).to.have.property('riskOfReoffending');
        // expect(instance.riskOfReoffending).to.be(expectedValueLiteral);
      });

      it('should have the property section (base name: "section")', function() {
        // TODO: update the code to test the property section
        expect(instance).to.have.property('section');
        // expect(instance.section).to.be(expectedValueLiteral);
      });

    });
  });

}));
