/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HmppsOffenderAssessmentApi);
  }
}(this, function(expect, HmppsOffenderAssessmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AuthorisationDto', function() {
      beforeEach(function() {
        instance = new HmppsOffenderAssessmentApi.AuthorisationDto();
      });

      it('should create an instance of AuthorisationDto', function() {
        // TODO: update the code to test AuthorisationDto
        expect(instance).to.be.a(HmppsOffenderAssessmentApi.AuthorisationDto);
      });

      it('should have the property oasysOffenderId (base name: "oasysOffenderId")', function() {
        // TODO: update the code to test the property oasysOffenderId
        expect(instance).to.have.property('oasysOffenderId');
        // expect(instance.oasysOffenderId).to.be(expectedValueLiteral);
      });

      it('should have the property oasysUserCode (base name: "oasysUserCode")', function() {
        // TODO: update the code to test the property oasysUserCode
        expect(instance).to.have.property('oasysUserCode');
        // expect(instance.oasysUserCode).to.be(expectedValueLiteral);
      });

      it('should have the property offenderPermissionLevel (base name: "offenderPermissionLevel")', function() {
        // TODO: update the code to test the property offenderPermissionLevel
        expect(instance).to.have.property('offenderPermissionLevel');
        // expect(instance.offenderPermissionLevel).to.be(expectedValueLiteral);
      });

      it('should have the property offenderPermissionResource (base name: "offenderPermissionResource")', function() {
        // TODO: update the code to test the property offenderPermissionResource
        expect(instance).to.have.property('offenderPermissionResource');
        // expect(instance.offenderPermissionResource).to.be(expectedValueLiteral);
      });

    });
  });

}));
