/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HmppsOffenderAssessmentApi);
  }
}(this, function(expect, HmppsOffenderAssessmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BasicSentencePlanDto', function() {
      beforeEach(function() {
        instance = new HmppsOffenderAssessmentApi.BasicSentencePlanDto();
      });

      it('should create an instance of BasicSentencePlanDto', function() {
        // TODO: update the code to test BasicSentencePlanDto
        expect(instance).to.be.a(HmppsOffenderAssessmentApi.BasicSentencePlanDto);
      });

      it('should have the property basicSentencePlanItems (base name: "basicSentencePlanItems")', function() {
        // TODO: update the code to test the property basicSentencePlanItems
        expect(instance).to.have.property('basicSentencePlanItems');
        // expect(instance.basicSentencePlanItems).to.be(expectedValueLiteral);
      });

      it('should have the property createdDate (base name: "createdDate")', function() {
        // TODO: update the code to test the property createdDate
        expect(instance).to.have.property('createdDate');
        // expect(instance.createdDate).to.be(expectedValueLiteral);
      });

      it('should have the property sentencePlanId (base name: "sentencePlanId")', function() {
        // TODO: update the code to test the property sentencePlanId
        expect(instance).to.have.property('sentencePlanId');
        // expect(instance.sentencePlanId).to.be(expectedValueLiteral);
      });

    });
  });

}));
