/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HmppsOffenderAssessmentApi);
  }
}(this, function(expect, HmppsOffenderAssessmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InterventionDto', function() {
      beforeEach(function() {
        instance = new HmppsOffenderAssessmentApi.InterventionDto();
      });

      it('should create an instance of InterventionDto', function() {
        // TODO: update the code to test InterventionDto
        expect(instance).to.be.a(HmppsOffenderAssessmentApi.InterventionDto);
      });

      it('should have the property copiedForward (base name: "copiedForward")', function() {
        // TODO: update the code to test the property copiedForward
        expect(instance).to.have.property('copiedForward');
        // expect(instance.copiedForward).to.be(expectedValueLiteral);
      });

      it('should have the property interventionCode (base name: "interventionCode")', function() {
        // TODO: update the code to test the property interventionCode
        expect(instance).to.have.property('interventionCode');
        // expect(instance.interventionCode).to.be(expectedValueLiteral);
      });

      it('should have the property interventionComment (base name: "interventionComment")', function() {
        // TODO: update the code to test the property interventionComment
        expect(instance).to.have.property('interventionComment');
        // expect(instance.interventionComment).to.be(expectedValueLiteral);
      });

      it('should have the property interventionDescription (base name: "interventionDescription")', function() {
        // TODO: update the code to test the property interventionDescription
        expect(instance).to.have.property('interventionDescription');
        // expect(instance.interventionDescription).to.be(expectedValueLiteral);
      });

      it('should have the property interventionMeasure (base name: "interventionMeasure")', function() {
        // TODO: update the code to test the property interventionMeasure
        expect(instance).to.have.property('interventionMeasure');
        // expect(instance.interventionMeasure).to.be(expectedValueLiteral);
      });

      it('should have the property timescale (base name: "timescale")', function() {
        // TODO: update the code to test the property timescale
        expect(instance).to.have.property('timescale');
        // expect(instance.timescale).to.be(expectedValueLiteral);
      });

      it('should have the property whoDoingWork (base name: "whoDoingWork")', function() {
        // TODO: update the code to test the property whoDoingWork
        expect(instance).to.have.property('whoDoingWork');
        // expect(instance.whoDoingWork).to.be(expectedValueLiteral);
      });

    });
  });

}));
