/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HmppsOffenderAssessmentApi);
  }
}(this, function(expect, HmppsOffenderAssessmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Ogrs3Dto', function() {
      beforeEach(function() {
        instance = new HmppsOffenderAssessmentApi.Ogrs3Dto();
      });

      it('should create an instance of Ogrs3Dto', function() {
        // TODO: update the code to test Ogrs3Dto
        expect(instance).to.be.a(HmppsOffenderAssessmentApi.Ogrs3Dto);
      });

      it('should have the property ogrs31Year (base name: "ogrs3_1Year")', function() {
        // TODO: update the code to test the property ogrs31Year
        expect(instance).to.have.property('ogrs31Year');
        // expect(instance.ogrs31Year).to.be(expectedValueLiteral);
      });

      it('should have the property ogrs32Year (base name: "ogrs3_2Year")', function() {
        // TODO: update the code to test the property ogrs32Year
        expect(instance).to.have.property('ogrs32Year');
        // expect(instance.ogrs32Year).to.be(expectedValueLiteral);
      });

      it('should have the property reconvictionRisk (base name: "reconvictionRisk")', function() {
        // TODO: update the code to test the property reconvictionRisk
        expect(instance).to.have.property('reconvictionRisk');
        // expect(instance.reconvictionRisk).to.be(expectedValueLiteral);
      });

    });
  });

}));
