/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HmppsOffenderAssessmentApi);
  }
}(this, function(expect, HmppsOffenderAssessmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('QuestionDto', function() {
      beforeEach(function() {
        instance = new HmppsOffenderAssessmentApi.QuestionDto();
      });

      it('should create an instance of QuestionDto', function() {
        // TODO: update the code to test QuestionDto
        expect(instance).to.be.a(HmppsOffenderAssessmentApi.QuestionDto);
      });

      it('should have the property answer (base name: "answer")', function() {
        // TODO: update the code to test the property answer
        expect(instance).to.have.property('answer');
        // expect(instance.answer).to.be(expectedValueLiteral);
      });

      it('should have the property displayOrder (base name: "displayOrder")', function() {
        // TODO: update the code to test the property displayOrder
        expect(instance).to.have.property('displayOrder');
        // expect(instance.displayOrder).to.be(expectedValueLiteral);
      });

      it('should have the property displayScore (base name: "displayScore")', function() {
        // TODO: update the code to test the property displayScore
        expect(instance).to.have.property('displayScore');
        // expect(instance.displayScore).to.be(expectedValueLiteral);
      });

      it('should have the property oasysQuestionId (base name: "oasysQuestionId")', function() {
        // TODO: update the code to test the property oasysQuestionId
        expect(instance).to.have.property('oasysQuestionId');
        // expect(instance.oasysQuestionId).to.be(expectedValueLiteral);
      });

      it('should have the property questionText (base name: "questionText")', function() {
        // TODO: update the code to test the property questionText
        expect(instance).to.have.property('questionText');
        // expect(instance.questionText).to.be(expectedValueLiteral);
      });

      it('should have the property refQuestionCode (base name: "refQuestionCode")', function() {
        // TODO: update the code to test the property refQuestionCode
        expect(instance).to.have.property('refQuestionCode');
        // expect(instance.refQuestionCode).to.be(expectedValueLiteral);
      });

      it('should have the property refQuestionId (base name: "refQuestionId")', function() {
        // TODO: update the code to test the property refQuestionId
        expect(instance).to.have.property('refQuestionId');
        // expect(instance.refQuestionId).to.be(expectedValueLiteral);
      });

    });
  });

}));
