/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HmppsOffenderAssessmentApi);
  }
}(this, function(expect, HmppsOffenderAssessmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RefAnswerDto', function() {
      beforeEach(function() {
        instance = new HmppsOffenderAssessmentApi.RefAnswerDto();
      });

      it('should create an instance of RefAnswerDto', function() {
        // TODO: update the code to test RefAnswerDto
        expect(instance).to.be.a(HmppsOffenderAssessmentApi.RefAnswerDto);
      });

      it('should have the property refAnswerCode (base name: "refAnswerCode")', function() {
        // TODO: update the code to test the property refAnswerCode
        expect(instance).to.have.property('refAnswerCode');
        // expect(instance.refAnswerCode).to.be(expectedValueLiteral);
      });

      it('should have the property refAnswerId (base name: "refAnswerId")', function() {
        // TODO: update the code to test the property refAnswerId
        expect(instance).to.have.property('refAnswerId');
        // expect(instance.refAnswerId).to.be(expectedValueLiteral);
      });

      it('should have the property refDisplaySort (base name: "refDisplaySort")', function() {
        // TODO: update the code to test the property refDisplaySort
        expect(instance).to.have.property('refDisplaySort');
        // expect(instance.refDisplaySort).to.be(expectedValueLiteral);
      });

    });
  });

}));
