/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HmppsOffenderAssessmentApi);
  }
}(this, function(expect, HmppsOffenderAssessmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RefAssessmentDto', function() {
      beforeEach(function() {
        instance = new HmppsOffenderAssessmentApi.RefAssessmentDto();
      });

      it('should create an instance of RefAssessmentDto', function() {
        // TODO: update the code to test RefAssessmentDto
        expect(instance).to.be.a(HmppsOffenderAssessmentApi.RefAssessmentDto);
      });

      it('should have the property oasysScoringAlgorithmVersion (base name: "oasysScoringAlgorithmVersion")', function() {
        // TODO: update the code to test the property oasysScoringAlgorithmVersion
        expect(instance).to.have.property('oasysScoringAlgorithmVersion');
        // expect(instance.oasysScoringAlgorithmVersion).to.be(expectedValueLiteral);
      });

      it('should have the property refAssVersionCode (base name: "refAssVersionCode")', function() {
        // TODO: update the code to test the property refAssVersionCode
        expect(instance).to.have.property('refAssVersionCode');
        // expect(instance.refAssVersionCode).to.be(expectedValueLiteral);
      });

      it('should have the property refAssessmentVersionId (base name: "refAssessmentVersionId")', function() {
        // TODO: update the code to test the property refAssessmentVersionId
        expect(instance).to.have.property('refAssessmentVersionId');
        // expect(instance.refAssessmentVersionId).to.be(expectedValueLiteral);
      });

      it('should have the property refModuleCode (base name: "refModuleCode")', function() {
        // TODO: update the code to test the property refModuleCode
        expect(instance).to.have.property('refModuleCode');
        // expect(instance.refModuleCode).to.be(expectedValueLiteral);
      });

      it('should have the property refSections (base name: "refSections")', function() {
        // TODO: update the code to test the property refSections
        expect(instance).to.have.property('refSections');
        // expect(instance.refSections).to.be(expectedValueLiteral);
      });

      it('should have the property versionNumber (base name: "versionNumber")', function() {
        // TODO: update the code to test the property versionNumber
        expect(instance).to.have.property('versionNumber');
        // expect(instance.versionNumber).to.be(expectedValueLiteral);
      });

    });
  });

}));
