/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.AnswerDto = factory(root.HmppsOffenderAssessmentApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AnswerDto model module.
   * @module model/AnswerDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AnswerDto</code>.
   * @alias module:model/AnswerDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AnswerDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnswerDto} obj Optional instance to populate.
   * @return {module:model/AnswerDto} The populated <code>AnswerDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('displayOrder'))
        obj.displayOrder = ApiClient.convertToType(data['displayOrder'], 'Number');
      if (data.hasOwnProperty('freeFormText'))
        obj.freeFormText = ApiClient.convertToType(data['freeFormText'], 'String');
      if (data.hasOwnProperty('oasysAnswerId'))
        obj.oasysAnswerId = ApiClient.convertToType(data['oasysAnswerId'], 'Number');
      if (data.hasOwnProperty('ogpScore'))
        obj.ogpScore = ApiClient.convertToType(data['ogpScore'], 'Number');
      if (data.hasOwnProperty('ovpScore'))
        obj.ovpScore = ApiClient.convertToType(data['ovpScore'], 'Number');
      if (data.hasOwnProperty('qaRawScore'))
        obj.qaRawScore = ApiClient.convertToType(data['qaRawScore'], 'Number');
      if (data.hasOwnProperty('refAnswerCode'))
        obj.refAnswerCode = ApiClient.convertToType(data['refAnswerCode'], 'String');
      if (data.hasOwnProperty('refAnswerId'))
        obj.refAnswerId = ApiClient.convertToType(data['refAnswerId'], 'Number');
      if (data.hasOwnProperty('staticText'))
        obj.staticText = ApiClient.convertToType(data['staticText'], 'String');
    }
    return obj;
  }

  /**
   * Answer Display Order
   * @member {Number} displayOrder
   */
  exports.prototype.displayOrder = undefined;

  /**
   * Free form answer text
   * @member {String} freeFormText
   */
  exports.prototype.freeFormText = undefined;

  /**
   * Answer ID
   * @member {Number} oasysAnswerId
   */
  exports.prototype.oasysAnswerId = undefined;

  /**
   * OGP score 
   * @member {Number} ogpScore
   */
  exports.prototype.ogpScore = undefined;

  /**
   * OVP score
   * @member {Number} ovpScore
   */
  exports.prototype.ovpScore = undefined;

  /**
   * QA raw score
   * @member {Number} qaRawScore
   */
  exports.prototype.qaRawScore = undefined;

  /**
   * Reference Answer Code
   * @member {String} refAnswerCode
   */
  exports.prototype.refAnswerCode = undefined;

  /**
   * Reference Answer ID
   * @member {Number} refAnswerId
   */
  exports.prototype.refAnswerId = undefined;

  /**
   * Static text
   * @member {String} staticText
   */
  exports.prototype.staticText = undefined;

  return exports;

}));
