/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.AssessmentNeedDto = factory(root.HmppsOffenderAssessmentApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AssessmentNeedDto model module.
   * @module model/AssessmentNeedDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AssessmentNeedDto</code>.
   * @alias module:model/AssessmentNeedDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AssessmentNeedDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssessmentNeedDto} obj Optional instance to populate.
   * @return {module:model/AssessmentNeedDto} The populated <code>AssessmentNeedDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('flaggedAsNeed'))
        obj.flaggedAsNeed = ApiClient.convertToType(data['flaggedAsNeed'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('overThreshold'))
        obj.overThreshold = ApiClient.convertToType(data['overThreshold'], 'Boolean');
      if (data.hasOwnProperty('riskOfHarm'))
        obj.riskOfHarm = ApiClient.convertToType(data['riskOfHarm'], 'Boolean');
      if (data.hasOwnProperty('riskOfReoffending'))
        obj.riskOfReoffending = ApiClient.convertToType(data['riskOfReoffending'], 'Boolean');
      if (data.hasOwnProperty('section'))
        obj.section = ApiClient.convertToType(data['section'], 'String');
    }
    return obj;
  }

  /**
   * Low scoring are flagged
   * @member {Boolean} flaggedAsNeed
   */
  exports.prototype.flaggedAsNeed = undefined;

  /**
   * Need name
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Over Crimiogenic Need score threshold
   * @member {Boolean} overThreshold
   */
  exports.prototype.overThreshold = undefined;

  /**
   * Related to risk of harm
   * @member {Boolean} riskOfHarm
   */
  exports.prototype.riskOfHarm = undefined;

  /**
   * Related to risk of reoffending
   * @member {Boolean} riskOfReoffending
   */
  exports.prototype.riskOfReoffending = undefined;

  /**
   * Section Header
   * @member {module:model/AssessmentNeedDto.SectionEnum} section
   */
  exports.prototype.section = undefined;


  /**
   * Allowed values for the <code>section</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SectionEnum = {
    /**
     * value: "OFFENDING_INFO"
     * @const
     */
    OFFENDING_INFO: "OFFENDING_INFO",

    /**
     * value: "ANALYSIS_OF_OFFENCES"
     * @const
     */
    ANALYSIS_OF_OFFENCES: "ANALYSIS_OF_OFFENCES",

    /**
     * value: "ACCOMMODATION"
     * @const
     */
    ACCOMMODATION: "ACCOMMODATION",

    /**
     * value: "EDUCATION_TRAINING_AND_EMPLOYABILITY"
     * @const
     */
    EDUCATION_TRAINING_AND_EMPLOYABILITY: "EDUCATION_TRAINING_AND_EMPLOYABILITY",

    /**
     * value: "FINANCIAL_MANAGEMENT_AND_INCOME"
     * @const
     */
    FINANCIAL_MANAGEMENT_AND_INCOME: "FINANCIAL_MANAGEMENT_AND_INCOME",

    /**
     * value: "RELATIONSHIPS"
     * @const
     */
    RELATIONSHIPS: "RELATIONSHIPS",

    /**
     * value: "LIFESTYLE_AND_ASSOCIATES"
     * @const
     */
    LIFESTYLE_AND_ASSOCIATES: "LIFESTYLE_AND_ASSOCIATES",

    /**
     * value: "DRUG_MISUSE"
     * @const
     */
    DRUG_MISUSE: "DRUG_MISUSE",

    /**
     * value: "ALCOHOL_MISUSE"
     * @const
     */
    ALCOHOL_MISUSE: "ALCOHOL_MISUSE",

    /**
     * value: "EMOTIONAL_WELL_BEING"
     * @const
     */
    EMOTIONAL_WELL_BEING: "EMOTIONAL_WELL_BEING",

    /**
     * value: "THINKING_AND_BEHAVIOUR"
     * @const
     */
    THINKING_AND_BEHAVIOUR: "THINKING_AND_BEHAVIOUR",

    /**
     * value: "ATTITUDES"
     * @const
     */
    ATTITUDES: "ATTITUDES",

    /**
     * value: "HEATH_AND_OTHER_CONSIDERATIONS"
     * @const
     */
    HEATH_AND_OTHER_CONSIDERATIONS: "HEATH_AND_OTHER_CONSIDERATIONS"
  };

  return exports;

}));
