/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssessmentNeedDto', 'model/SectionDto', 'model/SentenceDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AssessmentNeedDto'), require('./SectionDto'), require('./SentenceDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.AssessmentDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.AssessmentNeedDto, root.HmppsOffenderAssessmentApi.SectionDto, root.HmppsOffenderAssessmentApi.SentenceDto);
  }
}(this, function(ApiClient, AssessmentNeedDto, SectionDto, SentenceDto) {
  'use strict';

  /**
   * The AssessmentDto model module.
   * @module model/AssessmentDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AssessmentDto</code>.
   * @alias module:model/AssessmentDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AssessmentDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssessmentDto} obj Optional instance to populate.
   * @return {module:model/AssessmentDto} The populated <code>AssessmentDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('assessmentId'))
        obj.assessmentId = ApiClient.convertToType(data['assessmentId'], 'Number');
      if (data.hasOwnProperty('assessmentStatus'))
        obj.assessmentStatus = ApiClient.convertToType(data['assessmentStatus'], 'String');
      if (data.hasOwnProperty('assessmentType'))
        obj.assessmentType = ApiClient.convertToType(data['assessmentType'], 'String');
      if (data.hasOwnProperty('assessorName'))
        obj.assessorName = ApiClient.convertToType(data['assessorName'], 'String');
      if (data.hasOwnProperty('childSafeguardingIndicated'))
        obj.childSafeguardingIndicated = ApiClient.convertToType(data['childSafeguardingIndicated'], 'Boolean');
      if (data.hasOwnProperty('completedDateTime'))
        obj.completedDateTime = ApiClient.convertToType(data['completedDateTime'], 'Date');
      if (data.hasOwnProperty('createdDateTime'))
        obj.createdDateTime = ApiClient.convertToType(data['createdDateTime'], 'Date');
      if (data.hasOwnProperty('historicStatus'))
        obj.historicStatus = ApiClient.convertToType(data['historicStatus'], 'String');
      if (data.hasOwnProperty('layer3SentencePlanNeeds'))
        obj.layer3SentencePlanNeeds = ApiClient.convertToType(data['layer3SentencePlanNeeds'], [AssessmentNeedDto]);
      if (data.hasOwnProperty('refAssessmentId'))
        obj.refAssessmentId = ApiClient.convertToType(data['refAssessmentId'], 'Number');
      if (data.hasOwnProperty('refAssessmentOasysScoringAlgorithmVersion'))
        obj.refAssessmentOasysScoringAlgorithmVersion = ApiClient.convertToType(data['refAssessmentOasysScoringAlgorithmVersion'], 'Number');
      if (data.hasOwnProperty('refAssessmentVersionCode'))
        obj.refAssessmentVersionCode = ApiClient.convertToType(data['refAssessmentVersionCode'], 'String');
      if (data.hasOwnProperty('refAssessmentVersionNumber'))
        obj.refAssessmentVersionNumber = ApiClient.convertToType(data['refAssessmentVersionNumber'], 'String');
      if (data.hasOwnProperty('sections'))
        obj.sections = ApiClient.convertToType(data['sections'], [SectionDto]);
      if (data.hasOwnProperty('sentence'))
        obj.sentence = ApiClient.convertToType(data['sentence'], [SentenceDto]);
      if (data.hasOwnProperty('voidedDateTime'))
        obj.voidedDateTime = ApiClient.convertToType(data['voidedDateTime'], 'Date');
    }
    return obj;
  }

  /**
   * Assessment primary key (OASysSetPK)
   * @member {Number} assessmentId
   */
  exports.prototype.assessmentId = undefined;

  /**
   * Assessment Status
   * @member {String} assessmentStatus
   */
  exports.prototype.assessmentStatus = undefined;

  /**
   * Assessment Type
   * @member {String} assessmentType
   */
  exports.prototype.assessmentType = undefined;

  /**
   * AssessorName
   * @member {String} assessorName
   */
  exports.prototype.assessorName = undefined;

  /**
   * Child Safeguarding flat
   * @member {Boolean} childSafeguardingIndicated
   */
  exports.prototype.childSafeguardingIndicated = undefined;

  /**
   * Completed Date
   * @member {Date} completedDateTime
   */
  exports.prototype.completedDateTime = undefined;

  /**
   * Created Date
   * @member {Date} createdDateTime
   */
  exports.prototype.createdDateTime = undefined;

  /**
   * Assessment Group Historic Status
   * @member {String} historicStatus
   */
  exports.prototype.historicStatus = undefined;

  /**
   * Criminogenic Needs
   * @member {Array.<module:model/AssessmentNeedDto>} layer3SentencePlanNeeds
   */
  exports.prototype.layer3SentencePlanNeeds = undefined;

  /**
   * Assessment Reference Version
   * @member {Number} refAssessmentId
   */
  exports.prototype.refAssessmentId = undefined;

  /**
   * Assessment Scoring Algorithm Version
   * @member {Number} refAssessmentOasysScoringAlgorithmVersion
   */
  exports.prototype.refAssessmentOasysScoringAlgorithmVersion = undefined;

  /**
   * Assessment Reference Version Code
   * @member {String} refAssessmentVersionCode
   */
  exports.prototype.refAssessmentVersionCode = undefined;

  /**
   * Assessment Reference Version
   * @member {String} refAssessmentVersionNumber
   */
  exports.prototype.refAssessmentVersionNumber = undefined;

  /**
   * Assessment Sections
   * @member {Array.<module:model/SectionDto>} sections
   */
  exports.prototype.sections = undefined;

  /**
   * Sentences
   * @member {Array.<module:model/SentenceDto>} sentence
   */
  exports.prototype.sentence = undefined;

  /**
   * Voided Date
   * @member {Date} voidedDateTime
   */
  exports.prototype.voidedDateTime = undefined;

  return exports;

}));
