/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.AuthorisationDto = factory(root.HmppsOffenderAssessmentApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AuthorisationDto model module.
   * @module model/AuthorisationDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AuthorisationDto</code>.
   * @alias module:model/AuthorisationDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AuthorisationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthorisationDto} obj Optional instance to populate.
   * @return {module:model/AuthorisationDto} The populated <code>AuthorisationDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('oasysOffenderId'))
        obj.oasysOffenderId = ApiClient.convertToType(data['oasysOffenderId'], 'Number');
      if (data.hasOwnProperty('oasysUserCode'))
        obj.oasysUserCode = ApiClient.convertToType(data['oasysUserCode'], 'String');
      if (data.hasOwnProperty('offenderPermissionLevel'))
        obj.offenderPermissionLevel = ApiClient.convertToType(data['offenderPermissionLevel'], 'String');
      if (data.hasOwnProperty('offenderPermissionResource'))
        obj.offenderPermissionResource = ApiClient.convertToType(data['offenderPermissionResource'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} oasysOffenderId
   */
  exports.prototype.oasysOffenderId = undefined;

  /**
   * @member {String} oasysUserCode
   */
  exports.prototype.oasysUserCode = undefined;

  /**
   * @member {module:model/AuthorisationDto.OffenderPermissionLevelEnum} offenderPermissionLevel
   */
  exports.prototype.offenderPermissionLevel = undefined;

  /**
   * @member {module:model/AuthorisationDto.OffenderPermissionResourceEnum} offenderPermissionResource
   */
  exports.prototype.offenderPermissionResource = undefined;


  /**
   * Allowed values for the <code>offenderPermissionLevel</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OffenderPermissionLevelEnum = {
    /**
     * value: "UNAUTHORISED"
     * @const
     */
    UNAUTHORISED: "UNAUTHORISED",

    /**
     * value: "READ_ONLY"
     * @const
     */
    READ_ONLY: "READ_ONLY",

    /**
     * value: "WRITE"
     * @const
     */
    WRITE: "WRITE"
  };


  /**
   * Allowed values for the <code>offenderPermissionResource</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OffenderPermissionResourceEnum = {
    /**
     * value: "SENTENCE_PLAN"
     * @const
     */
    SENTENCE_PLAN: "SENTENCE_PLAN"
  };

  return exports;

}));
