/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicSentencePlanItemDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BasicSentencePlanItemDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.BasicSentencePlanDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.BasicSentencePlanItemDto);
  }
}(this, function(ApiClient, BasicSentencePlanItemDto) {
  'use strict';

  /**
   * The BasicSentencePlanDto model module.
   * @module model/BasicSentencePlanDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BasicSentencePlanDto</code>.
   * @alias module:model/BasicSentencePlanDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BasicSentencePlanDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BasicSentencePlanDto} obj Optional instance to populate.
   * @return {module:model/BasicSentencePlanDto} The populated <code>BasicSentencePlanDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('basicSentencePlanItems'))
        obj.basicSentencePlanItems = ApiClient.convertToType(data['basicSentencePlanItems'], [BasicSentencePlanItemDto]);
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'Date');
      if (data.hasOwnProperty('sentencePlanId'))
        obj.sentencePlanId = ApiClient.convertToType(data['sentencePlanId'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/BasicSentencePlanItemDto>} basicSentencePlanItems
   */
  exports.prototype.basicSentencePlanItems = undefined;

  /**
   * @member {Date} createdDate
   */
  exports.prototype.createdDate = undefined;

  /**
   * @member {Number} sentencePlanId
   */
  exports.prototype.sentencePlanId = undefined;

  return exports;

}));
