/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RefElementDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RefElementDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.BasicSentencePlanItemDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.RefElementDto);
  }
}(this, function(ApiClient, RefElementDto) {
  'use strict';

  /**
   * The BasicSentencePlanItemDto model module.
   * @module model/BasicSentencePlanItemDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BasicSentencePlanItemDto</code>.
   * @alias module:model/BasicSentencePlanItemDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BasicSentencePlanItemDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BasicSentencePlanItemDto} obj Optional instance to populate.
   * @return {module:model/BasicSentencePlanItemDto} The populated <code>BasicSentencePlanItemDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('basicSentPlanObjId'))
        obj.basicSentPlanObjId = ApiClient.convertToType(data['basicSentPlanObjId'], 'Number');
      if (data.hasOwnProperty('dateCompleted'))
        obj.dateCompleted = ApiClient.convertToType(data['dateCompleted'], 'Date');
      if (data.hasOwnProperty('dateOpened'))
        obj.dateOpened = ApiClient.convertToType(data['dateOpened'], 'Date');
      if (data.hasOwnProperty('includeInPlan'))
        obj.includeInPlan = ApiClient.convertToType(data['includeInPlan'], 'Boolean');
      if (data.hasOwnProperty('measureText'))
        obj.measureText = ApiClient.convertToType(data['measureText'], 'String');
      if (data.hasOwnProperty('objectiveText'))
        obj.objectiveText = ApiClient.convertToType(data['objectiveText'], 'String');
      if (data.hasOwnProperty('offenceBehaviourLink'))
        obj.offenceBehaviourLink = RefElementDto.constructFromObject(data['offenceBehaviourLink']);
      if (data.hasOwnProperty('problemAreaCompInd'))
        obj.problemAreaCompInd = ApiClient.convertToType(data['problemAreaCompInd'], 'Boolean');
      if (data.hasOwnProperty('timescalesText'))
        obj.timescalesText = ApiClient.convertToType(data['timescalesText'], 'String');
      if (data.hasOwnProperty('whatWorkText'))
        obj.whatWorkText = ApiClient.convertToType(data['whatWorkText'], 'String');
      if (data.hasOwnProperty('whoWillDoWorkText'))
        obj.whoWillDoWorkText = ApiClient.convertToType(data['whoWillDoWorkText'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} basicSentPlanObjId
   */
  exports.prototype.basicSentPlanObjId = undefined;

  /**
   * @member {Date} dateCompleted
   */
  exports.prototype.dateCompleted = undefined;

  /**
   * @member {Date} dateOpened
   */
  exports.prototype.dateOpened = undefined;

  /**
   * @member {Boolean} includeInPlan
   */
  exports.prototype.includeInPlan = undefined;

  /**
   * @member {String} measureText
   */
  exports.prototype.measureText = undefined;

  /**
   * @member {String} objectiveText
   */
  exports.prototype.objectiveText = undefined;

  /**
   * @member {module:model/RefElementDto} offenceBehaviourLink
   */
  exports.prototype.offenceBehaviourLink = undefined;

  /**
   * @member {Boolean} problemAreaCompInd
   */
  exports.prototype.problemAreaCompInd = undefined;

  /**
   * @member {String} timescalesText
   */
  exports.prototype.timescalesText = undefined;

  /**
   * @member {String} whatWorkText
   */
  exports.prototype.whatWorkText = undefined;

  /**
   * @member {String} whoWillDoWorkText
   */
  exports.prototype.whoWillDoWorkText = undefined;

  return exports;

}));
