/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ObjectiveDto', 'model/QuestionDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ObjectiveDto'), require('./QuestionDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.FullSentencePlanDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.ObjectiveDto, root.HmppsOffenderAssessmentApi.QuestionDto);
  }
}(this, function(ApiClient, ObjectiveDto, QuestionDto) {
  'use strict';

  /**
   * The FullSentencePlanDto model module.
   * @module model/FullSentencePlanDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FullSentencePlanDto</code>.
   * @alias module:model/FullSentencePlanDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>FullSentencePlanDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FullSentencePlanDto} obj Optional instance to populate.
   * @return {module:model/FullSentencePlanDto} The populated <code>FullSentencePlanDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('completedDate'))
        obj.completedDate = ApiClient.convertToType(data['completedDate'], 'Date');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'Date');
      if (data.hasOwnProperty('oasysSetId'))
        obj.oasysSetId = ApiClient.convertToType(data['oasysSetId'], 'Number');
      if (data.hasOwnProperty('objectives'))
        obj.objectives = ApiClient.convertToType(data['objectives'], [ObjectiveDto]);
      if (data.hasOwnProperty('questions'))
        obj.questions = ApiClient.convertToType(data['questions'], {'String': QuestionDto});
    }
    return obj;
  }

  /**
   * @member {Date} completedDate
   */
  exports.prototype.completedDate = undefined;

  /**
   * @member {Date} createdDate
   */
  exports.prototype.createdDate = undefined;

  /**
   * @member {Number} oasysSetId
   */
  exports.prototype.oasysSetId = undefined;

  /**
   * @member {Array.<module:model/ObjectiveDto>} objectives
   */
  exports.prototype.objectives = undefined;

  /**
   * @member {Object.<String, module:model/QuestionDto>} questions
   */
  exports.prototype.questions = undefined;

  return exports;

}));
