/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.FullSentencePlanSummaryDto = factory(root.HmppsOffenderAssessmentApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The FullSentencePlanSummaryDto model module.
   * @module model/FullSentencePlanSummaryDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FullSentencePlanSummaryDto</code>.
   * @alias module:model/FullSentencePlanSummaryDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>FullSentencePlanSummaryDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FullSentencePlanSummaryDto} obj Optional instance to populate.
   * @return {module:model/FullSentencePlanSummaryDto} The populated <code>FullSentencePlanSummaryDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('completedDate'))
        obj.completedDate = ApiClient.convertToType(data['completedDate'], 'Date');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'Date');
      if (data.hasOwnProperty('oasysSetId'))
        obj.oasysSetId = ApiClient.convertToType(data['oasysSetId'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Date} completedDate
   */
  exports.prototype.completedDate = undefined;

  /**
   * @member {Date} createdDate
   */
  exports.prototype.createdDate = undefined;

  /**
   * @member {Number} oasysSetId
   */
  exports.prototype.oasysSetId = undefined;

  return exports;

}));
