/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CriminogenicNeedDto', 'model/InterventionDto', 'model/ObjectiveMeasureDto', 'model/RefElementDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CriminogenicNeedDto'), require('./InterventionDto'), require('./ObjectiveMeasureDto'), require('./RefElementDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.ObjectiveDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.CriminogenicNeedDto, root.HmppsOffenderAssessmentApi.InterventionDto, root.HmppsOffenderAssessmentApi.ObjectiveMeasureDto, root.HmppsOffenderAssessmentApi.RefElementDto);
  }
}(this, function(ApiClient, CriminogenicNeedDto, InterventionDto, ObjectiveMeasureDto, RefElementDto) {
  'use strict';

  /**
   * The ObjectiveDto model module.
   * @module model/ObjectiveDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ObjectiveDto</code>.
   * @alias module:model/ObjectiveDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ObjectiveDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ObjectiveDto} obj Optional instance to populate.
   * @return {module:model/ObjectiveDto} The populated <code>ObjectiveDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'Date');
      if (data.hasOwnProperty('criminogenicNeeds'))
        obj.criminogenicNeeds = ApiClient.convertToType(data['criminogenicNeeds'], [CriminogenicNeedDto]);
      if (data.hasOwnProperty('howMeasured'))
        obj.howMeasured = ApiClient.convertToType(data['howMeasured'], 'String');
      if (data.hasOwnProperty('interventions'))
        obj.interventions = ApiClient.convertToType(data['interventions'], [InterventionDto]);
      if (data.hasOwnProperty('objectiveCode'))
        obj.objectiveCode = ApiClient.convertToType(data['objectiveCode'], 'String');
      if (data.hasOwnProperty('objectiveComment'))
        obj.objectiveComment = ApiClient.convertToType(data['objectiveComment'], 'String');
      if (data.hasOwnProperty('objectiveDescription'))
        obj.objectiveDescription = ApiClient.convertToType(data['objectiveDescription'], 'String');
      if (data.hasOwnProperty('objectiveHeading'))
        obj.objectiveHeading = ApiClient.convertToType(data['objectiveHeading'], 'String');
      if (data.hasOwnProperty('objectiveMeasure'))
        obj.objectiveMeasure = ObjectiveMeasureDto.constructFromObject(data['objectiveMeasure']);
      if (data.hasOwnProperty('objectiveType'))
        obj.objectiveType = RefElementDto.constructFromObject(data['objectiveType']);
    }
    return obj;
  }

  /**
   * @member {Date} createdDate
   */
  exports.prototype.createdDate = undefined;

  /**
   * @member {Array.<module:model/CriminogenicNeedDto>} criminogenicNeeds
   */
  exports.prototype.criminogenicNeeds = undefined;

  /**
   * @member {String} howMeasured
   */
  exports.prototype.howMeasured = undefined;

  /**
   * @member {Array.<module:model/InterventionDto>} interventions
   */
  exports.prototype.interventions = undefined;

  /**
   * @member {String} objectiveCode
   */
  exports.prototype.objectiveCode = undefined;

  /**
   * @member {String} objectiveComment
   */
  exports.prototype.objectiveComment = undefined;

  /**
   * @member {String} objectiveDescription
   */
  exports.prototype.objectiveDescription = undefined;

  /**
   * @member {String} objectiveHeading
   */
  exports.prototype.objectiveHeading = undefined;

  /**
   * @member {module:model/ObjectiveMeasureDto} objectiveMeasure
   */
  exports.prototype.objectiveMeasure = undefined;

  /**
   * @member {module:model/RefElementDto} objectiveType
   */
  exports.prototype.objectiveType = undefined;

  return exports;

}));
