/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RefElementDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RefElementDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.ObjectiveMeasureDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.RefElementDto);
  }
}(this, function(ApiClient, RefElementDto) {
  'use strict';

  /**
   * The ObjectiveMeasureDto model module.
   * @module model/ObjectiveMeasureDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ObjectiveMeasureDto</code>.
   * @alias module:model/ObjectiveMeasureDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ObjectiveMeasureDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ObjectiveMeasureDto} obj Optional instance to populate.
   * @return {module:model/ObjectiveMeasureDto} The populated <code>ObjectiveMeasureDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('comments'))
        obj.comments = ApiClient.convertToType(data['comments'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = RefElementDto.constructFromObject(data['status']);
    }
    return obj;
  }

  /**
   * @member {String} comments
   */
  exports.prototype.comments = undefined;

  /**
   * @member {module:model/RefElementDto} status
   */
  exports.prototype.status = undefined;

  return exports;

}));
