/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.OffenderDto = factory(root.HmppsOffenderAssessmentApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The OffenderDto model module.
   * @module model/OffenderDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OffenderDto</code>.
   * @alias module:model/OffenderDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>OffenderDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OffenderDto} obj Optional instance to populate.
   * @return {module:model/OffenderDto} The populated <code>OffenderDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('bookingNumber'))
        obj.bookingNumber = ApiClient.convertToType(data['bookingNumber'], 'String');
      if (data.hasOwnProperty('crn'))
        obj.crn = ApiClient.convertToType(data['crn'], 'String');
      if (data.hasOwnProperty('croNumber'))
        obj.croNumber = ApiClient.convertToType(data['croNumber'], 'String');
      if (data.hasOwnProperty('familyName'))
        obj.familyName = ApiClient.convertToType(data['familyName'], 'String');
      if (data.hasOwnProperty('forename1'))
        obj.forename1 = ApiClient.convertToType(data['forename1'], 'String');
      if (data.hasOwnProperty('forename2'))
        obj.forename2 = ApiClient.convertToType(data['forename2'], 'String');
      if (data.hasOwnProperty('forename3'))
        obj.forename3 = ApiClient.convertToType(data['forename3'], 'String');
      if (data.hasOwnProperty('legacyCmsProbNumber'))
        obj.legacyCmsProbNumber = ApiClient.convertToType(data['legacyCmsProbNumber'], 'String');
      if (data.hasOwnProperty('limitedAccessOffender'))
        obj.limitedAccessOffender = ApiClient.convertToType(data['limitedAccessOffender'], 'Boolean');
      if (data.hasOwnProperty('mergePncNumber'))
        obj.mergePncNumber = ApiClient.convertToType(data['mergePncNumber'], 'String');
      if (data.hasOwnProperty('mergedOasysOffenderId'))
        obj.mergedOasysOffenderId = ApiClient.convertToType(data['mergedOasysOffenderId'], 'Number');
      if (data.hasOwnProperty('nomisId'))
        obj.nomisId = ApiClient.convertToType(data['nomisId'], 'String');
      if (data.hasOwnProperty('oasysOffenderId'))
        obj.oasysOffenderId = ApiClient.convertToType(data['oasysOffenderId'], 'Number');
      if (data.hasOwnProperty('pnc'))
        obj.pnc = ApiClient.convertToType(data['pnc'], 'String');
      if (data.hasOwnProperty('riskToOthers'))
        obj.riskToOthers = ApiClient.convertToType(data['riskToOthers'], 'String');
      if (data.hasOwnProperty('riskToSelf'))
        obj.riskToSelf = ApiClient.convertToType(data['riskToSelf'], 'String');
    }
    return obj;
  }

  /**
   * NOMIS Booking Number
   * @member {String} bookingNumber
   */
  exports.prototype.bookingNumber = undefined;

  /**
   * Delius CRN
   * @member {String} crn
   */
  exports.prototype.crn = undefined;

  /**
   * CRO Number
   * @member {String} croNumber
   */
  exports.prototype.croNumber = undefined;

  /**
   * Family Name
   * @member {String} familyName
   */
  exports.prototype.familyName = undefined;

  /**
   * Forename
   * @member {String} forename1
   */
  exports.prototype.forename1 = undefined;

  /**
   * Middle Name
   * @member {String} forename2
   */
  exports.prototype.forename2 = undefined;

  /**
   * Middle Name
   * @member {String} forename3
   */
  exports.prototype.forename3 = undefined;

  /**
   * Legacy Case ID
   * @member {String} legacyCmsProbNumber
   */
  exports.prototype.legacyCmsProbNumber = undefined;

  /**
   * Limited Access Offender
   * @member {Boolean} limitedAccessOffender
   */
  exports.prototype.limitedAccessOffender = undefined;

  /**
   * Merged PNC Number
   * @member {String} mergePncNumber
   */
  exports.prototype.mergePncNumber = undefined;

  /**
   * Merged From Offender PK
   * @member {Number} mergedOasysOffenderId
   */
  exports.prototype.mergedOasysOffenderId = undefined;

  /**
   * NOMIS ID
   * @member {String} nomisId
   */
  exports.prototype.nomisId = undefined;

  /**
   * OASys Offender PK
   * @member {Number} oasysOffenderId
   */
  exports.prototype.oasysOffenderId = undefined;

  /**
   * PNC Number
   * @member {String} pnc
   */
  exports.prototype.pnc = undefined;

  /**
   * Risk to Others
   * @member {String} riskToOthers
   */
  exports.prototype.riskToOthers = undefined;

  /**
   * Risk to Others
   * @member {String} riskToSelf
   */
  exports.prototype.riskToSelf = undefined;

  return exports;

}));
