/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RefElementDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RefElementDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.OgpDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.RefElementDto);
  }
}(this, function(ApiClient, RefElementDto) {
  'use strict';

  /**
   * The OgpDto model module.
   * @module model/OgpDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OgpDto</code>.
   * @alias module:model/OgpDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>OgpDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OgpDto} obj Optional instance to populate.
   * @return {module:model/OgpDto} The populated <code>OgpDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ogp1Year'))
        obj.ogp1Year = ApiClient.convertToType(data['ogp1Year'], 'Number');
      if (data.hasOwnProperty('ogp2Year'))
        obj.ogp2Year = ApiClient.convertToType(data['ogp2Year'], 'Number');
      if (data.hasOwnProperty('ogpDynamicWeightedScore'))
        obj.ogpDynamicWeightedScore = ApiClient.convertToType(data['ogpDynamicWeightedScore'], 'Number');
      if (data.hasOwnProperty('ogpRisk'))
        obj.ogpRisk = RefElementDto.constructFromObject(data['ogpRisk']);
      if (data.hasOwnProperty('ogpStaticWeightedScore'))
        obj.ogpStaticWeightedScore = ApiClient.convertToType(data['ogpStaticWeightedScore'], 'Number');
      if (data.hasOwnProperty('ogpTotalWeightedScore'))
        obj.ogpTotalWeightedScore = ApiClient.convertToType(data['ogpTotalWeightedScore'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} ogp1Year
   */
  exports.prototype.ogp1Year = undefined;

  /**
   * @member {Number} ogp2Year
   */
  exports.prototype.ogp2Year = undefined;

  /**
   * @member {Number} ogpDynamicWeightedScore
   */
  exports.prototype.ogpDynamicWeightedScore = undefined;

  /**
   * @member {module:model/RefElementDto} ogpRisk
   */
  exports.prototype.ogpRisk = undefined;

  /**
   * @member {Number} ogpStaticWeightedScore
   */
  exports.prototype.ogpStaticWeightedScore = undefined;

  /**
   * @member {Number} ogpTotalWeightedScore
   */
  exports.prototype.ogpTotalWeightedScore = undefined;

  return exports;

}));
