/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RefElementDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RefElementDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.Ogrs3Dto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.RefElementDto);
  }
}(this, function(ApiClient, RefElementDto) {
  'use strict';

  /**
   * The Ogrs3Dto model module.
   * @module model/Ogrs3Dto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Ogrs3Dto</code>.
   * @alias module:model/Ogrs3Dto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Ogrs3Dto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ogrs3Dto} obj Optional instance to populate.
   * @return {module:model/Ogrs3Dto} The populated <code>Ogrs3Dto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ogrs3_1Year'))
        obj.ogrs31Year = ApiClient.convertToType(data['ogrs3_1Year'], 'Number');
      if (data.hasOwnProperty('ogrs3_2Year'))
        obj.ogrs32Year = ApiClient.convertToType(data['ogrs3_2Year'], 'Number');
      if (data.hasOwnProperty('reconvictionRisk'))
        obj.reconvictionRisk = RefElementDto.constructFromObject(data['reconvictionRisk']);
    }
    return obj;
  }

  /**
   * @member {Number} ogrs31Year
   */
  exports.prototype.ogrs31Year = undefined;

  /**
   * @member {Number} ogrs32Year
   */
  exports.prototype.ogrs32Year = undefined;

  /**
   * @member {module:model/RefElementDto} reconvictionRisk
   */
  exports.prototype.reconvictionRisk = undefined;

  return exports;

}));
