/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OgpDto', 'model/Ogrs3Dto', 'model/OvpDto', 'model/RefElementDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OgpDto'), require('./Ogrs3Dto'), require('./OvpDto'), require('./RefElementDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.PredictorDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.OgpDto, root.HmppsOffenderAssessmentApi.Ogrs3Dto, root.HmppsOffenderAssessmentApi.OvpDto, root.HmppsOffenderAssessmentApi.RefElementDto);
  }
}(this, function(ApiClient, OgpDto, Ogrs3Dto, OvpDto, RefElementDto) {
  'use strict';

  /**
   * The PredictorDto model module.
   * @module model/PredictorDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PredictorDto</code>.
   * @alias module:model/PredictorDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PredictorDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PredictorDto} obj Optional instance to populate.
   * @return {module:model/PredictorDto} The populated <code>PredictorDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('assessmentCompleted'))
        obj.assessmentCompleted = ApiClient.convertToType(data['assessmentCompleted'], 'Boolean');
      if (data.hasOwnProperty('completedDate'))
        obj.completedDate = ApiClient.convertToType(data['completedDate'], 'Date');
      if (data.hasOwnProperty('oasysSetId'))
        obj.oasysSetId = ApiClient.convertToType(data['oasysSetId'], 'Number');
      if (data.hasOwnProperty('ogp'))
        obj.ogp = OgpDto.constructFromObject(data['ogp']);
      if (data.hasOwnProperty('ogr3'))
        obj.ogr3 = Ogrs3Dto.constructFromObject(data['ogr3']);
      if (data.hasOwnProperty('otherRisk'))
        obj.otherRisk = RefElementDto.constructFromObject(data['otherRisk']);
      if (data.hasOwnProperty('ovp'))
        obj.ovp = OvpDto.constructFromObject(data['ovp']);
      if (data.hasOwnProperty('refAssessmentId'))
        obj.refAssessmentId = ApiClient.convertToType(data['refAssessmentId'], 'Number');
      if (data.hasOwnProperty('refAssessmentVersionCode'))
        obj.refAssessmentVersionCode = ApiClient.convertToType(data['refAssessmentVersionCode'], 'String');
      if (data.hasOwnProperty('refAssessmentVersionNumber'))
        obj.refAssessmentVersionNumber = ApiClient.convertToType(data['refAssessmentVersionNumber'], 'String');
      if (data.hasOwnProperty('voidedDateTime'))
        obj.voidedDateTime = ApiClient.convertToType(data['voidedDateTime'], 'Date');
    }
    return obj;
  }

  /**
   * @member {Boolean} assessmentCompleted
   */
  exports.prototype.assessmentCompleted = undefined;

  /**
   * @member {Date} completedDate
   */
  exports.prototype.completedDate = undefined;

  /**
   * @member {Number} oasysSetId
   */
  exports.prototype.oasysSetId = undefined;

  /**
   * @member {module:model/OgpDto} ogp
   */
  exports.prototype.ogp = undefined;

  /**
   * @member {module:model/Ogrs3Dto} ogr3
   */
  exports.prototype.ogr3 = undefined;

  /**
   * @member {module:model/RefElementDto} otherRisk
   */
  exports.prototype.otherRisk = undefined;

  /**
   * @member {module:model/OvpDto} ovp
   */
  exports.prototype.ovp = undefined;

  /**
   * @member {Number} refAssessmentId
   */
  exports.prototype.refAssessmentId = undefined;

  /**
   * @member {String} refAssessmentVersionCode
   */
  exports.prototype.refAssessmentVersionCode = undefined;

  /**
   * @member {String} refAssessmentVersionNumber
   */
  exports.prototype.refAssessmentVersionNumber = undefined;

  /**
   * @member {Date} voidedDateTime
   */
  exports.prototype.voidedDateTime = undefined;

  return exports;

}));
