/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AnswerDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AnswerDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.QuestionDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.AnswerDto);
  }
}(this, function(ApiClient, AnswerDto) {
  'use strict';

  /**
   * The QuestionDto model module.
   * @module model/QuestionDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>QuestionDto</code>.
   * @alias module:model/QuestionDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>QuestionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuestionDto} obj Optional instance to populate.
   * @return {module:model/QuestionDto} The populated <code>QuestionDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('answer'))
        obj.answer = AnswerDto.constructFromObject(data['answer']);
      if (data.hasOwnProperty('displayOrder'))
        obj.displayOrder = ApiClient.convertToType(data['displayOrder'], 'Number');
      if (data.hasOwnProperty('displayScore'))
        obj.displayScore = ApiClient.convertToType(data['displayScore'], 'Number');
      if (data.hasOwnProperty('oasysQuestionId'))
        obj.oasysQuestionId = ApiClient.convertToType(data['oasysQuestionId'], 'Number');
      if (data.hasOwnProperty('questionText'))
        obj.questionText = ApiClient.convertToType(data['questionText'], 'String');
      if (data.hasOwnProperty('refQuestionCode'))
        obj.refQuestionCode = ApiClient.convertToType(data['refQuestionCode'], 'String');
      if (data.hasOwnProperty('refQuestionId'))
        obj.refQuestionId = ApiClient.convertToType(data['refQuestionId'], 'Number');
    }
    return obj;
  }

  /**
   * Question Answer
   * @member {module:model/AnswerDto} answer
   */
  exports.prototype.answer = undefined;

  /**
   * Display Order
   * @member {Number} displayOrder
   */
  exports.prototype.displayOrder = undefined;

  /**
   * Display Score, example
   * @member {Number} displayScore
   */
  exports.prototype.displayScore = undefined;

  /**
   * Unique Question ID
   * @member {Number} oasysQuestionId
   */
  exports.prototype.oasysQuestionId = undefined;

  /**
   * Question Text
   * @member {String} questionText
   */
  exports.prototype.questionText = undefined;

  /**
   * Question Code
   * @member {String} refQuestionCode
   */
  exports.prototype.refQuestionCode = undefined;

  /**
   * Reference Question ID
   * @member {Number} refQuestionId
   */
  exports.prototype.refQuestionId = undefined;

  return exports;

}));
