/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RefSectionDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RefSectionDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.RefAssessmentDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.RefSectionDto);
  }
}(this, function(ApiClient, RefSectionDto) {
  'use strict';

  /**
   * The RefAssessmentDto model module.
   * @module model/RefAssessmentDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RefAssessmentDto</code>.
   * @alias module:model/RefAssessmentDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RefAssessmentDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RefAssessmentDto} obj Optional instance to populate.
   * @return {module:model/RefAssessmentDto} The populated <code>RefAssessmentDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('oasysScoringAlgorithmVersion'))
        obj.oasysScoringAlgorithmVersion = ApiClient.convertToType(data['oasysScoringAlgorithmVersion'], 'Number');
      if (data.hasOwnProperty('refAssVersionCode'))
        obj.refAssVersionCode = ApiClient.convertToType(data['refAssVersionCode'], 'String');
      if (data.hasOwnProperty('refAssessmentVersionId'))
        obj.refAssessmentVersionId = ApiClient.convertToType(data['refAssessmentVersionId'], 'Number');
      if (data.hasOwnProperty('refModuleCode'))
        obj.refModuleCode = ApiClient.convertToType(data['refModuleCode'], 'String');
      if (data.hasOwnProperty('refSections'))
        obj.refSections = ApiClient.convertToType(data['refSections'], [RefSectionDto]);
      if (data.hasOwnProperty('versionNumber'))
        obj.versionNumber = ApiClient.convertToType(data['versionNumber'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} oasysScoringAlgorithmVersion
   */
  exports.prototype.oasysScoringAlgorithmVersion = undefined;

  /**
   * @member {String} refAssVersionCode
   */
  exports.prototype.refAssVersionCode = undefined;

  /**
   * @member {Number} refAssessmentVersionId
   */
  exports.prototype.refAssessmentVersionId = undefined;

  /**
   * @member {String} refModuleCode
   */
  exports.prototype.refModuleCode = undefined;

  /**
   * @member {Array.<module:model/RefSectionDto>} refSections
   */
  exports.prototype.refSections = undefined;

  /**
   * @member {String} versionNumber
   */
  exports.prototype.versionNumber = undefined;

  return exports;

}));
