/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RefAnswerDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RefAnswerDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.RefQuestionDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.RefAnswerDto);
  }
}(this, function(ApiClient, RefAnswerDto) {
  'use strict';

  /**
   * The RefQuestionDto model module.
   * @module model/RefQuestionDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RefQuestionDto</code>.
   * @alias module:model/RefQuestionDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RefQuestionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RefQuestionDto} obj Optional instance to populate.
   * @return {module:model/RefQuestionDto} The populated <code>RefQuestionDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('refAnswers'))
        obj.refAnswers = ApiClient.convertToType(data['refAnswers'], [RefAnswerDto]);
      if (data.hasOwnProperty('refCtAreaEstCode'))
        obj.refCtAreaEstCode = ApiClient.convertToType(data['refCtAreaEstCode'], 'String');
      if (data.hasOwnProperty('refDisplaySort'))
        obj.refDisplaySort = ApiClient.convertToType(data['refDisplaySort'], 'Number');
      if (data.hasOwnProperty('refMandatoryIndicator'))
        obj.refMandatoryIndicator = ApiClient.convertToType(data['refMandatoryIndicator'], 'Boolean');
      if (data.hasOwnProperty('refQAWeighting'))
        obj.refQAWeighting = ApiClient.convertToType(data['refQAWeighting'], 'Number');
      if (data.hasOwnProperty('refQuestionCode'))
        obj.refQuestionCode = ApiClient.convertToType(data['refQuestionCode'], 'String');
      if (data.hasOwnProperty('refQuestionId'))
        obj.refQuestionId = ApiClient.convertToType(data['refQuestionId'], 'Number');
      if (data.hasOwnProperty('refQuestionText'))
        obj.refQuestionText = ApiClient.convertToType(data['refQuestionText'], 'String');
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/RefAnswerDto>} refAnswers
   */
  exports.prototype.refAnswers = undefined;

  /**
   * @member {String} refCtAreaEstCode
   */
  exports.prototype.refCtAreaEstCode = undefined;

  /**
   * @member {Number} refDisplaySort
   */
  exports.prototype.refDisplaySort = undefined;

  /**
   * @member {Boolean} refMandatoryIndicator
   */
  exports.prototype.refMandatoryIndicator = undefined;

  /**
   * @member {Number} refQAWeighting
   */
  exports.prototype.refQAWeighting = undefined;

  /**
   * @member {String} refQuestionCode
   */
  exports.prototype.refQuestionCode = undefined;

  /**
   * @member {Number} refQuestionId
   */
  exports.prototype.refQuestionId = undefined;

  /**
   * @member {String} refQuestionText
   */
  exports.prototype.refQuestionText = undefined;

  return exports;

}));
