/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/QuestionDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./QuestionDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.SectionDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.QuestionDto);
  }
}(this, function(ApiClient, QuestionDto) {
  'use strict';

  /**
   * The SectionDto model module.
   * @module model/SectionDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SectionDto</code>.
   * @alias module:model/SectionDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SectionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SectionDto} obj Optional instance to populate.
   * @return {module:model/SectionDto} The populated <code>SectionDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('assessmentId'))
        obj.assessmentId = ApiClient.convertToType(data['assessmentId'], 'Number');
      if (data.hasOwnProperty('lowScoreAttentionNeeded'))
        obj.lowScoreAttentionNeeded = ApiClient.convertToType(data['lowScoreAttentionNeeded'], 'Boolean');
      if (data.hasOwnProperty('questions'))
        obj.questions = ApiClient.convertToType(data['questions'], [QuestionDto]);
      if (data.hasOwnProperty('refAssessmentVersionCode'))
        obj.refAssessmentVersionCode = ApiClient.convertToType(data['refAssessmentVersionCode'], 'String');
      if (data.hasOwnProperty('refSectionCode'))
        obj.refSectionCode = ApiClient.convertToType(data['refSectionCode'], 'String');
      if (data.hasOwnProperty('refSectionCrimNeedScoreThreshold'))
        obj.refSectionCrimNeedScoreThreshold = ApiClient.convertToType(data['refSectionCrimNeedScoreThreshold'], 'Number');
      if (data.hasOwnProperty('refSectionVersionNumber'))
        obj.refSectionVersionNumber = ApiClient.convertToType(data['refSectionVersionNumber'], 'String');
      if (data.hasOwnProperty('sectionId'))
        obj.sectionId = ApiClient.convertToType(data['sectionId'], 'Number');
      if (data.hasOwnProperty('sectionOgpRawScore'))
        obj.sectionOgpRawScore = ApiClient.convertToType(data['sectionOgpRawScore'], 'Number');
      if (data.hasOwnProperty('sectionOgpWeightedScore'))
        obj.sectionOgpWeightedScore = ApiClient.convertToType(data['sectionOgpWeightedScore'], 'Number');
      if (data.hasOwnProperty('sectionOtherRawScore'))
        obj.sectionOtherRawScore = ApiClient.convertToType(data['sectionOtherRawScore'], 'Number');
      if (data.hasOwnProperty('sectionOtherWeightedScore'))
        obj.sectionOtherWeightedScore = ApiClient.convertToType(data['sectionOtherWeightedScore'], 'Number');
      if (data.hasOwnProperty('sectionOvpRawScore'))
        obj.sectionOvpRawScore = ApiClient.convertToType(data['sectionOvpRawScore'], 'Number');
      if (data.hasOwnProperty('sectionOvpWeightedScore'))
        obj.sectionOvpWeightedScore = ApiClient.convertToType(data['sectionOvpWeightedScore'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} assessmentId
   */
  exports.prototype.assessmentId = undefined;

  /**
   * @member {Boolean} lowScoreAttentionNeeded
   */
  exports.prototype.lowScoreAttentionNeeded = undefined;

  /**
   * @member {Array.<module:model/QuestionDto>} questions
   */
  exports.prototype.questions = undefined;

  /**
   * @member {String} refAssessmentVersionCode
   */
  exports.prototype.refAssessmentVersionCode = undefined;

  /**
   * @member {String} refSectionCode
   */
  exports.prototype.refSectionCode = undefined;

  /**
   * @member {Number} refSectionCrimNeedScoreThreshold
   */
  exports.prototype.refSectionCrimNeedScoreThreshold = undefined;

  /**
   * @member {String} refSectionVersionNumber
   */
  exports.prototype.refSectionVersionNumber = undefined;

  /**
   * @member {Number} sectionId
   */
  exports.prototype.sectionId = undefined;

  /**
   * @member {Number} sectionOgpRawScore
   */
  exports.prototype.sectionOgpRawScore = undefined;

  /**
   * @member {Number} sectionOgpWeightedScore
   */
  exports.prototype.sectionOgpWeightedScore = undefined;

  /**
   * @member {Number} sectionOtherRawScore
   */
  exports.prototype.sectionOtherRawScore = undefined;

  /**
   * @member {Number} sectionOtherWeightedScore
   */
  exports.prototype.sectionOtherWeightedScore = undefined;

  /**
   * @member {Number} sectionOvpRawScore
   */
  exports.prototype.sectionOvpRawScore = undefined;

  /**
   * @member {Number} sectionOvpWeightedScore
   */
  exports.prototype.sectionOvpWeightedScore = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  return exports;

}));
