/*
 * HMPPS Offender Assessment API
 * OASys Data API.
 *
 * OpenAPI spec version: 2020-09-02
 * Contact: feedback@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RefElementDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RefElementDto'));
  } else {
    // Browser globals (root is window)
    if (!root.HmppsOffenderAssessmentApi) {
      root.HmppsOffenderAssessmentApi = {};
    }
    root.HmppsOffenderAssessmentApi.SentenceDto = factory(root.HmppsOffenderAssessmentApi.ApiClient, root.HmppsOffenderAssessmentApi.RefElementDto);
  }
}(this, function(ApiClient, RefElementDto) {
  'use strict';

  /**
   * The SentenceDto model module.
   * @module model/SentenceDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SentenceDto</code>.
   * @alias module:model/SentenceDto
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SentenceDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SentenceDto} obj Optional instance to populate.
   * @return {module:model/SentenceDto} The populated <code>SentenceDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('activity'))
        obj.activity = ApiClient.convertToType(data['activity'], 'String');
      if (data.hasOwnProperty('cja'))
        obj.cja = ApiClient.convertToType(data['cja'], 'Boolean');
      if (data.hasOwnProperty('cjaSupervisionMonths'))
        obj.cjaSupervisionMonths = ApiClient.convertToType(data['cjaSupervisionMonths'], 'Number');
      if (data.hasOwnProperty('cjaUnpaidHours'))
        obj.cjaUnpaidHours = ApiClient.convertToType(data['cjaUnpaidHours'], 'Number');
      if (data.hasOwnProperty('custodial'))
        obj.custodial = ApiClient.convertToType(data['custodial'], 'Boolean');
      if (data.hasOwnProperty('offenceBlockType'))
        obj.offenceBlockType = RefElementDto.constructFromObject(data['offenceBlockType']);
      if (data.hasOwnProperty('offenceDate'))
        obj.offenceDate = ApiClient.convertToType(data['offenceDate'], 'Date');
      if (data.hasOwnProperty('orderType'))
        obj.orderType = RefElementDto.constructFromObject(data['orderType']);
      if (data.hasOwnProperty('sentenceCode'))
        obj.sentenceCode = ApiClient.convertToType(data['sentenceCode'], 'String');
      if (data.hasOwnProperty('sentenceDate'))
        obj.sentenceDate = ApiClient.convertToType(data['sentenceDate'], 'Date');
      if (data.hasOwnProperty('sentenceDescription'))
        obj.sentenceDescription = ApiClient.convertToType(data['sentenceDescription'], 'String');
      if (data.hasOwnProperty('sentenceLengthCustodyDays'))
        obj.sentenceLengthCustodyDays = ApiClient.convertToType(data['sentenceLengthCustodyDays'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} activity
   */
  exports.prototype.activity = undefined;

  /**
   * @member {Boolean} cja
   */
  exports.prototype.cja = undefined;

  /**
   * @member {Number} cjaSupervisionMonths
   */
  exports.prototype.cjaSupervisionMonths = undefined;

  /**
   * @member {Number} cjaUnpaidHours
   */
  exports.prototype.cjaUnpaidHours = undefined;

  /**
   * @member {Boolean} custodial
   */
  exports.prototype.custodial = undefined;

  /**
   * @member {module:model/RefElementDto} offenceBlockType
   */
  exports.prototype.offenceBlockType = undefined;

  /**
   * @member {Date} offenceDate
   */
  exports.prototype.offenceDate = undefined;

  /**
   * @member {module:model/RefElementDto} orderType
   */
  exports.prototype.orderType = undefined;

  /**
   * @member {String} sentenceCode
   */
  exports.prototype.sentenceCode = undefined;

  /**
   * @member {Date} sentenceDate
   */
  exports.prototype.sentenceDate = undefined;

  /**
   * @member {String} sentenceDescription
   */
  exports.prototype.sentenceDescription = undefined;

  /**
   * @member {Number} sentenceLengthCustodyDays
   */
  exports.prototype.sentenceLengthCustodyDays = undefined;

  return exports;

}));
